CREATE TABLE BANCASEGUROS.DIM_CANAL_VENTA (
    SK_CANAL_VENTA  INTEGER NOT NULL,
    CD_CANAL_VENTA  VARCHAR2(50),
    DS_CANAL_VENTA  VARCHAR2(300),
    FE_CARGA        DATE NOT NULL,
    FE_ACTUALIZA    DATE
);
--Creacion de base de datos
ALTER TABLE BANCASEGUROS.DIM_CANAL_VENTA ADD CONSTRAINT DIM_CANAL_VENTA_PK PRIMARY KEY ( SK_CANAL_VENTA );

CREATE TABLE BANCASEGUROS.DIM_LINEA_NEGOCIO (
    SK_LINEA_NEGOCIO  INTEGER NOT NULL,
    CD_LINEA_NEGOCIO  VARCHAR2(50),
    DS_LINEA_NEGOCIO  VARCHAR2(300),
    FE_CARGA          DATE NOT NULL,
    FE_ACTUALIZA      DATE
);



ALTER TABLE BANCASEGUROS.DIM_LINEA_NEGOCIO ADD CONSTRAINT DIM_LINEA_NEGOCIO_PK PRIMARY KEY ( SK_LINEA_NEGOCIO );

CREATE TABLE BANCASEGUROS.DIM_PRODUCTO (
    SK_PRODUCTO   INTEGER NOT NULL,
    CD_PRODUCTO   NVARCHAR2 (50),
    DS_PRODUCTO   NVARCHAR2 (200),
    FE_CARGA      DATE NOT NULL,
    FE_ACTUALIZA  DATE
);

ALTER TABLE BANCASEGUROS.DIM_PRODUCTO ADD CONSTRAINT DIM_PRODUCTO_PK PRIMARY KEY ( SK_PRODUCTO );


CREATE TABLE BANCASEGUROS.DIM_RAMO (
    SK_RAMO       INTEGER NOT NULL,
    CD_RAMO       VARCHAR2(50),
    DS_RAMO       VARCHAR2(300),
    FE_CARGA      DATE NOT NULL,
    FE_ACTUALIZA  DATE
);

ALTER TABLE BANCASEGUROS.DIM_RAMO ADD CONSTRAINT DIM_RAMO_PK PRIMARY KEY ( SK_RAMO );



CREATE TABLE BANCASEGUROS.DIM_SOCIO (
    SK_SOCIO      INTEGER NOT NULL,
    CD_SOCIO      VARCHAR2(50),
    DS_SOCIO      VARCHAR2(300),
    FE_CARGA      DATE NOT NULL,
    FE_ACTUALIZA  DATE
);

ALTER TABLE BANCASEGUROS.DIM_SOCIO ADD CONSTRAINT DIM_SOCIO_PK PRIMARY KEY ( SK_SOCIO );




CREATE TABLE BANCASEGUROS.DIM_TIPO_PRIMA (
    SK_TIPO_PRIMA  INTEGER NOT NULL,
    CD_TIPO_PRIMA  VARCHAR2(50),
    DS_TIPO_PRIMA  VARCHAR2(300),
    FE_CARGA       DATE NOT NULL,
    FE_ACTUALIZA   DATE
);

ALTER TABLE BANCASEGUROS.DIM_TIPO_PRIMA ADD CONSTRAINT DIM_TIPO_PRIMA_PK PRIMARY KEY ( SK_TIPO_PRIMA );



CREATE TABLE BANCASEGUROS.FCT_BANCA_SEGURO (
    SK_PRODUCTO           INTEGER NOT NULL,
    SK_SOCIO              INTEGER NOT NULL,
    SK_CANAL_VENTA        INTEGER NOT NULL,
    SK_TIPO_PRIMA         INTEGER NOT NULL,
    SK_LINEA_NEGOCIO      INTEGER NOT NULL,
    SK_RAMO               INTEGER NOT NULL,
    CONCEPTO              VARCHAR2(100) NOT NULL,
    FUJO_STOK             VARCHAR2(30),
    PORCENTAJE_RAMO       NUMBER(5, 3) NOT NULL,
    VALOR_TOTAL_CONCEPTO  NUMBER(38, 3) NOT NULL,
    VALOR_CONCEPTO        NUMBER(38, 3) NOT NULL,
    SK_FECHA_CONCEPTO     INTEGER NOT NULL,
    FECHA_CONCEPTO        DATE NOT NULL
);


CREATE SEQUENCE BANCASEGUROS.SQN_DIM_CANAL_VENTA START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE BANCASEGUROS.SQN_DIM_LINEA_NEGOCIO START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE BANCASEGUROS.SQN_DIM_PRODUCTO START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE BANCASEGUROS.SQN_DIM_RAMO START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE BANCASEGUROS.SQN_DIM_SOCIO START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE BANCASEGUROS.SQN_DIM_TIPO_PRIMA START WITH 1 NOCACHE ORDER;

--GRANT SELECT ON BANCASEGUROS.DIM_SOCIO TO CONSULBO;
--GRANT SELECT ON BANCASEGUROS.DIM_RAMO TO CONSULBO; 
--GRANT SELECT ON BANCASEGUROS.DIM_LINEA_NEGOCIO TO CONSULBO; 
--GRANT SELECT ON BANCASEGUROS.DIM_PRODUCTO TO CONSULBO; 
--GRANT SELECT ON BANCASEGUROS.DIM_CANAL_VENTA TO CONSULBO;
--GRANT SELECT ON BANCASEGUROS.DIM_TIPO_PRIMA TO CONSULBO; 
--GRANT SELECT ON BANCASEGUROS.FCT_BANCA_SEGURO TO CONSULBO; 

